version: '3.9'

services:

  prisma-py-sandbox-db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-must_set_env}
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - local-dayo
    ports:
      - "${DB_PORT:-5678}:5432"
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  local-dayo:
    name: ${DB_NETWORK_NAME:-must-set-env}