from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Post',
    'Tag',
    'PostTag',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'posts': 'Post',
    },
    'Post': {
        'user': 'User',
        'tags': 'Tag',
        'PostTag': 'PostTag',
    },
    'Tag': {
        'posts': 'Post',
        'PostTag': 'PostTag',
    },
    'PostTag': {
        'post': 'Post',
        'tag': 'Tag',
    },
}

# fmt: on